/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'error-container': '#93000a',
        'surface-bright': '#353944',
        'on-error-container': '#ffdad6',
        'on-tertiary': '#00354a',
        'inverse-on-surface': '#2c303b',
        'on-secondary-fixed-variant': '#2f2ebe',
        'on-secondary-container': '#b0b2ff',
        'on-primary': '#00363a',
        'surface-dim': '#0f131d',
        'surface': '#0f131d',
        'surface-container': '#1c1f2a',
        'secondary': '#c0c1ff',
        'outline-variant': '#3b494b',
        'secondary-container': '#3131c0',
        'on-error': '#690005',
        'tertiary': '#eef7ff',
        'on-primary-fixed': '#002022',
        'on-primary-fixed-variant': '#004f54',
        'inverse-primary': '#006970',
        'primary-fixed': '#7df4ff',
        'background': '#0f131d',
        'on-tertiary-container': '#00668b',
        'on-surface-variant': '#b9cacb',
        'surface-container-low': '#171b26',
        'on-primary-container': '#006970',
        'surface-container-high': '#262a35',
        'tertiary-fixed-dim': '#7bd0ff',
        'on-surface': '#dfe2f1',
        'error': '#ffb4ab',
        'inverse-surface': '#dfe2f1',
        'on-tertiary-fixed-variant': '#004c69',
        'outline': '#849495',
        'secondary-fixed': '#e1e0ff',
        'primary-container': '#00f0ff',
        'on-secondary': '#1000a9',
        'secondary-container-light': '#6366f1',
        'tertiary-container': '#aee0ff',
        'on-secondary-light': '#e0e7ff',
        'surface-tint': '#00dbe9',
        'on-tertiary-fixed': '#001e2c',
        'surface-container-highest': '#313540',
        'surface-variant': '#313540',
        'primary-fixed-dim': '#00dbe9',
        'on-background': '#dfe2f1',
        'secondary-fixed-dim': '#c0c1ff',
        'on-secondary-fixed': '#07006c',
        'primary': '#dbfcff',

        // Telemetry status tokens (from DESIGN.md)
        'status-ok': '#10b981',
        'status-warn': '#f59e0b',
        'status-crit': '#f43f5e',
        'status-info': '#0ea5e9',
        'status-muted': '#64748b',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-sm': '0.5rem',
        'gutter-mobile': '0.75rem',
        'space-xs': '0.25rem',
        'space-lg': '1.25rem',
        margin: '2rem',
        'space-md': '0.75rem',
        gutter: '1.25rem',
        'margin-mobile': '1rem',
        'space-xl': '2rem',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        'title-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'code-sm': ['Inter', 'monospace'],
        'label-caps': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['1rem', { lineHeight: '1.5rem', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg-mobile': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.015em', fontWeight: '600' }],
        display: ['3rem', { lineHeight: '3.5rem', letterSpacing: '-0.025em', fontWeight: '700' }],
        'title-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0em', fontWeight: '600' }],
        'body-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.01em', fontWeight: '400' }],
        'headline-md': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['1.125rem', { lineHeight: '1.5rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg': ['2rem', { lineHeight: '2.5rem', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-md': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.02em', fontWeight: '500' }],
        'code-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0em', fontWeight: '400' }],
        'label-caps': ['0.6875rem', { lineHeight: '0.875rem', letterSpacing: '0.06em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
